version: '3.8'

services:
  # постгрес
  db:
    image: postgres:15-alpine
    container_name: bookstore_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bookstore"]
      interval: 10s
      timeout: 5s
      retries: 5

  #  джава
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore_app
    ports:
      - "8084:8084"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookstore
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true

      # тимчасово відключу
      SPRING_H2_CONSOLE_ENABLED: false
    networks:
      - bookstore-network
    restart: on-failure

    # pgadmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bookstore_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bookstore-network
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  bookstore-network:
    driver: bridge