server.port=8084

spring.web.resources.add-mappings=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:/sql/sql.sql

# JWT conf
application.security.jwt.secret-key=XEADXnVxBA9xmf+5rEsf80SDTo+rLGV+qOvuJYlIKIg=
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# OAuth2
spring.security.oauth2.client.registration.google.client-id=1024291528624-26p850le6r64st297k9q4at46bla0jmd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile


# File upload
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB