server.port=8084

spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.web.resources.add-mappings=false

spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:/sql/sql.sql

# --- JWT Configuration ---
# ????????? ???? ??? ??????? ??????? (??????? 256 ??? ??? HS256).
# ??? ???????????? ????????? 256-?????? ???? (hex).
application.security.jwt.secret-key=XEADXnVxBA9xmf+5rEsf80SDTo+rLGV+qOvuJYlIKIg=

# ??? ????? Access Token ? ???????????? (?????????, 1 ???? = 86400000)
application.security.jwt.expiration=86400000

# ??? ????? Refresh Token ? ???????????? (?????????, 7 ???? = 604800000)
application.security.jwt.refresh-token.expiration=604800000

spring.security.oauth2.client.registration.google.client-id=1024291528624-26p850le6r64st297k9q4at46bla0jmd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
