
services:
  # фронтенд (React + nginx)
  frontend:
    build:
      context: ../front/my-app
      dockerfile: Dockerfile
    container_name: bookstore-frontend
    ports:
      - "5173:80"
    depends_on:
      - app
    networks:
      - bookstore-network

  # постгрес
  db:
    image: postgres:15-alpine
    container_name: bookstore_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bookstore"]
      interval: 10s
      timeout: 5s
      retries: 5

  #  джава
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-app
    ports:
      - "8084:8084"
    depends_on:
      db:
        condition: service_healthy
    environment:
      CLIENT_URL: http://localhost:5173
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookstore
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true

      # тимчасово відключу
      SPRING_H2_CONSOLE_ENABLED: false
    networks:
      - bookstore-network
    restart: on-failure

    # pgadmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bookstore_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bookstore-network
    depends_on:
      - db

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe_listener
    command: listen --forward-to http://bookstore-app:8084/api/payment/webhook --api-key sk_test_51StbDCBLY4dgBx7C7eoYp9ME0FDQph4xIY1Mw8R67TZBSozy9nrBlQIVE9ghnWly3vZr7xKEal0LL7fcjltGrjiL00RKqUGoN8
    networks:
      - bookstore-network
    depends_on:
      - app
    restart: on-failure


volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  bookstore-network:
    driver: bridge